### ISSUE TITLE
Pass IP/Login/Pass via inbound msg.payload

### ISSUE THREAD

**Issue by MagnAxiom** [alhafoudh/node-red-contrib-mikrotik2#1]
First, let me say how excited I am to see this node!!!

Is it possible to pass the IP/login/pass inbound to the node vs hard coding it inside the module?

**Comment by alhafoudh** [comment]
IP, login and password are now stored through common node-red interface for storing sensitive  configuration options which are encrypted in the process.

Passing credentials through messages could expose these sensitive information.

What is you use-case?

**Comment by MagnAxiom** [comment]
I have a 1500+ mikrotik network, and i'm building a "management" application to standardize passwords and firmwares.  right now I use MikroNode as a module, but think an actual node implementation would be cleaner.  I'm inside a private network, so this wouldn't be passing over the internet.

**Comment by shaheen69** [comment]
Hi,

Thanks for the node-red implementation of Mikrotik. It has helped me quite a lot in my work with managing Mikrotik devices. 

I also have a similar use case where I have several Mikrotik devices and would like to pass a single command to all these devices at once. Would be nice to send the host and login credentials As parameters vie the flow. 

Regards,

Shaheen

**Comment by konne** [comment]
closed and followed up in https://github.com/node-red-contrib/node-red-contrib-mikrotik/issues/22
