### ISSUE TITLE
After update RouterOS to 6.45.1 api login don't work any more

### ISSUE THREAD

**Issue by portalek** [alhafoudh/node-red-contrib-mikrotik2#3]
Mikrotik changed login api, is it possible to update?

**Comment by portalek** [comment]
https://wiki.mikrotik.com/wiki/Manual:API#Initial_login

**Comment by rmukhtarov** [comment]
Hello.
The same issue.

**Comment by 0nikola1** [comment]
https://github.com/niksy111/node-red-contrib-mikrotik3

**Comment by rmukhtarov** [comment]
Actually problem with not node-red-contrib-mikrotik.
This node has dependency as mikronode-ng.
For solving problem you can find /.node-red/node_modules/mikronode-ng/lib/connection.js file and In connections.js - Connection.prototype.loginStateMachine(), around line 564, replace
lc.write('/login'); _(this).status = 'Waiting for challenge';
with
lc.write('/login', { "=name" : _(this).user, "=password" : _(this).password }); _(this).status = 'Waiting for Response';

**Comment by 0nikola1** [comment]
I solved that problem with my mikronode-ng2 which i put on npm but still not on github
