### ISSUE TITLE
consolidate

### ISSUE THREAD

**Issue by konne** [alhafoudh/node-red-contrib-mikrotik2#6]
Hi, I really like to consolidate this package so that the node-red-contrib-mikrotik, node-red-contrib-mikrotik2, node-red-contrib-mikrotik3 finds and ends.
Are you willing to transfer / handover the npm and this repo to me?

bye Konrad

**Comment by alhafoudh** [comment]
Sure I can do that.

**Comment by konne** [comment]
@alhafoudh thanks for the invite. Please can you give me also access to the npm package, so that I can start to implement GitHub action to make an automated push to all repos.

**Comment by alhafoudh** [comment]
Done :)

**Comment by konne** [comment]
@alhafoudh thanks I will take care in the next days
