### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by soosp** [alhafoudh/node-red-contrib-mikrotik2#8]
**Is your feature request related to a problem? Please describe.**
If you want to access a MikroTik device on an unreliable network it is unsafe without SSL/TLS.

**Describe the solution you'd like**
Use api-ssl instead of api with even if with self signed or custom CA signed certificates.

**Describe alternatives you've considered**
There are not any alternatives of encrypted connections on unreliable networks.

**Additional context**
-

**Comment by konne** [comment]
@soosp closed, because this is not a separate repo any more. Will be followed up in https://github.com/node-red-contrib/node-red-contrib-mikrotik/issues/29
